### ISSUE TITLE
Not compatible with Node 10.x

### ISSUE THREAD

**Issue by xtvdata** [joeldavidw/node-red-contrib-beacon-scanner#4]
While in the documentation of Node-Red is still mentioned that installer installs node-v8 LTE, currently it does install node-v10.

Unfortunately node-red-contrib-beacon-scanner cannot be used with that version.

However installing it results in this strange behavior in Palette:

![node-red-contrib-beacon-scanner](https://user-images.githubusercontent.com/36301293/50843489-136e4b80-1369-11e9-98f3-e94402de4d64.png)

anyway no errors/warnings appear in the log.

**Comment by krambriw** [comment]
Noticed this as well, is it possible to fix?

**Comment by HanYangZhao** [comment]
I think it's caused by noble's dependency on "bluetooth-hci-socket": "^0.5.1". Node 10 support was only added in version 0.5.3

**Comment by joeldavidw** [comment]
Thanks @HanYangZhao for the information. I will test it out tomorrow and push the fix.

**Comment by HanYangZhao** [comment]
Maybe it's better to use https://github.com/abandonware/noble? It seems to be more maintained than the original repo

**Comment by joeldavidw** [comment]
Thanks! Was looking at the repo awhile back just didn't had the time to implement it. I will test it out today!

**Comment by joeldavidw** [comment]
I have updated the affected pages with @abandoneware/noble and its seems to be working on node v10.
