### ISSUE TITLE
Compile error, "npm i noble"

### ISSUE THREAD

**Issue by MatsA** [joeldavidw/node-red-contrib-beacon-scanner#5]
Hi ! Tried to install the Node according to Your instructions, but are getting a compile error in "npm i noble" Running Buster, fresh install, on RPi 3 with Node V10
Please find an enclosed logfile from installation.
[node-red-contrib-beacon-scanner 0.0.8_log.txt](https://github.com/joeldavidw/node-red-contrib-beacon-scanner/files/3708853/node-red-contrib-beacon-scanner.0.0.8_log.txt)
Any idea ? Thanks

**Comment by MatsA** [comment]
Did a further check and think that Your installation instruction for RPi should be changed to `npm i @abandonware/noble`, but didn't get it right anyhow.

**Comment by joeldavidw** [comment]
Updated that installation step as it is not necessary and erroneous. Thanks!
