### ISSUE TITLE
BLE scanner on HA

### ISSUE THREAD

**Issue by werdy64** [joeldavidw/node-red-contrib-beacon-scanner#7]
Hi,
This NOD works perfectly on the NR installed on the Pi. But it is not possible to install on the NR of Home Assistant. Do you have any idea?

**Comment by joeldavidw** [comment]
Is Home Assistant running on a Pi?

**Comment by werdy64** [comment]
Yes. HA is running on Pi4 and NR installed on HA as addon.

**Comment by joeldavidw** [comment]
Are you using hassos? If you are you would not be able to install the plugin as the home assistant and Node Red would be running in docker containers and it is currently not supported. Even if you could install the plugin I believe you would face issues trying to give the Node Red container access to the bluetooth interface.

One way you could try is to run Raspberry Pi OS and install both HA and Node Red separately on the pi.

**Comment by werdy64** [comment]
Ok. I'll try it. Thank you vary much for responce.

вт, 11 авг. 2020 г., 12:28 Joel-David Wong <notifications@github.com>:
