### ISSUE TITLE
Beacon scanner on BBB in Node-Red

### ISSUE THREAD

**Issue by 2sMichiel** [joeldavidw/node-red-contrib-beacon-scanner#8]
I have this beacon scanner working on Raspberry PI in Node Red.
I have a Beagle Bone Black with a wireless connectivity cape. Bluetooth is working. in CLI i receive bluetooth packages. I'm not able to receive the Beacon information in Node Red on the beaglebone. Is there a way to use this node with node red on a beaglebone?

**Comment by joeldavidw** [comment]
Assuming that you are running Ubuntu or Debian on your beaglebone could try installing the following packages:
```sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev```
